#SPDX-FileCopyrightText: 2024 Linnea Gräf <nea@nea.moe>
#
#SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "NotFirmament"
SPDX-PackageSupplier = "Linnea Gräf <nea@nea.moe>"
SPDX-PackageDownloadLocation = "https://github.com/nea89o/NotFirmament"

[[annotations]]
path = ["**/*.kt", "**/*.java"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = ["src/main/resources/**/*.png", "src/main/resources/**/*.mcmeta"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = ["src/main/resources/assets/notfirmament/shaders/**/*"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = "translations/**/*.json"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = "**/fabric.mod.json"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = ["src/main/resources/assets/notfirmament/gui/**/*.xml"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = "**/*.gradle.kts"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = ["**/META-INF/services/*"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = ["src/test/resources/testdata/**/*.snbt"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "NotFirmament Contributors"]

[[annotations]]
path = ["src/main/resources/legacy_data/*.json"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = ["PrismarineJS Minecraft Data"]
